// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string    `json:"id"`
	PostID    string    `json:"postID"`
	ParentID  *string   `json:"parentID,omitempty"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

type CommentConnection struct {
	TotalCount *int32         `json:"totalCount,omitempty"`
	Edges      []*CommentEdge `json:"edges,omitempty"`
	PageInfo   *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type CommentNotify struct {
	PostID  string `json:"postID"`
	ID      string `json:"id"`
	Content string `json:"content"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Post struct {
	ID              string             `json:"id"`
	Title           string             `json:"title"`
	Content         string             `json:"content"`
	Comments        *CommentConnection `json:"comments"`
	CommentsAllowed bool               `json:"commentsAllowed"`
	CreatedAt       time.Time          `json:"createdAt"`
}

type Query struct {
}

type Subscription struct {
}
