env: "local"         #"local","debug","prod"#
storage: "postgres" #"postgres","in-memory"#
query_cache: "100"
storage_connect:
  sql_driver: "postgres"
  sql_user: "postgres"
  sql_password: "postgres"
  sql_address: "localhost"
  sql_port: "5432"
  sql_dbname: "client-services"
  sql_sslmode: "disable"
http_server:
  url: "localhost"
  port: "8080"
  timeout: "4s"
  idle_timeout: "60s"